openapi: 3.0.2
info:
 title: Demo
 version: "1.0.0"
paths:
  /sessions:
    post:
     description: Add new session
     responses:
       '200':
         description: Login sucsesfull
         content:
          application/json:
           schema:
            items: 
               $ref: '#/components/schemas/login'
components:
  schemas:
    User:
     properties:
      account title:
       type: string
      name user:
       type: string
